---
- name: Site play
  hosts: 192.168.1.111
  become: true
  gather_facts: true

  tasks:
    - name: Zorg dat apache2 is geïnstalleerd
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
    - name: Opzettelijke fout
      ansible.builtin.fail:
        msg: "Dit is een opzettelijke foutmelding voor testdoeleinden."
      when: true  # Verander naar 'false' om de fout te vermijden ivm test
