name: Terraform CI/CD (ESXi)

on:
  push:
    paths:
      - "terraform/**"
  pull_request:
    paths:
      - "terraform/**"

jobs:
  ci:
    name: Lint/Validate/Plan
    runs-on: [self-hosted]   # pas aan naar jouw runner labels
    defaults:
      run:
        working-directory: terraform
    env:
      TF_IN_AUTOMATION: "true"
      TF_VAR_esxi_password: ${{ secrets.TF_VAR_esxi_password }}  # overschrijft default
    steps:
      - uses: actions/checkout@v4

      - name: Check ovftool present
        run: |
          if ! command -v ovftool >/dev/null 2>&1; then
            echo "::error::ovftool is not installed or not in PATH on this self-hosted runner."
            echo "Install VMware ovftool and ensure 'ovftool' is in PATH, then re-run."
            exit 1
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Cache .terraform
        uses: actions/cache@v4
        with:
          path: terraform/.terraform
          key: ${{ runner.os }}-tf-${{ hashFiles('terraform/**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-tf-

      - name: terraform fmt (check)
        run: terraform fmt -check -diff

      - name: Install tflint (local ./bin) + add to PATH
        run: |
          mkdir -p bin
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh \
            | bash -s -- -b "$PWD/bin"
          echo "$PWD/bin" >> "$GITHUB_PATH"
          which tflint
          tflint --version

      - name: TFLint (best practices)
        run: |
          tflint --init
          tflint

      - name: terraform init
        run: terraform init -input=false

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan -input=false -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

  apply:
    name: Apply (main only)
    runs-on: [self-hosted]
    needs: [ci]
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: terraform
    env:
      TF_IN_AUTOMATION: "true"
      TF_VAR_esxi_password: ${{ secrets.TF_VAR_esxi_password }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "1.7.5" }

      - name: Check ovftool present
        run: |
          if ! command -v ovftool >/dev/null 2>&1; then
            echo "::error::ovftool is not installed or not in PATH on this self-hosted runner."
            exit 1
          fi

      - name: terraform init
        run: terraform init -input=false

      - name: terraform apply
        run: terraform apply -input=false -auto-approve
